version: '3'
services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file:
      - .env
    depends_on:
      - mongo-import

  mongo-import:
    image: mongo
    container_name: mongo_import
    volumes:
      - ./data:/data
    command: mongoimport --host mongodb --db $MONGO_DATABASE --collection $MONGO_COLLECTION --file /data/verzeichnis.json --jsonArray

  app:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb